name: lakehouse

networks:
  lakehouse_network:
    name: lakehouse_network
    external: true

services:
  ranger-mysql:
    image: mysql:8.0
    container_name: ranger-mysql
    networks:
      - lakehouse_network
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ranger_db
      MYSQL_USER: ranger
      MYSQL_PASSWORD: ranger123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ranger", "-pranger123"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
